MagicVilla_Web/Controllers/VillaController.cs
using AutoMapper;
using MagicVilla_Utility;
using MagicVilla_Web.Models;
using MagicVilla_Web.Models.Dto.VillaDTO;
using MagicVilla_Web.Services.IServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace MagicVilla_Web.Controllers
{
    public class VillaController : Controller
    {
        private readonly IVillaService _service;
        private readonly IMapper _mapper;
        public VillaController(IVillaService service, IMapper mapper)
        {
            _service = service;
            _mapper = mapper;
        }

        // GET ALL
        public async Task<IActionResult> IndexVilla()
        {
            var result = new List<VillaDTO>();
            var res = await _service.GetAllAsync<APIResponse>();
            if (res != null || res.IsSuccess)
            {
                result = JsonConvert.DeserializeObject<List<VillaDTO>>(Convert.ToString(res.Result));

            }
            return View(result);
        }

        // GET
        [HttpGet]
        public async Task<IActionResult> GetVilla()
        {
            var res = await _service.GetAllAsync<APIResponse>();
            if (res != null || res.IsSuccess)
            {
                return View(JsonConvert.DeserializeObject<VillaDTO>(Convert.ToString(res.Result)));

            }
            TempData["error"] = "Something went wrong!";
            return View(new VillaDTO());
        }

        // CREATE
        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> CreateVilla()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateVilla(VillaCreateDTO model)
        {
            if (ModelState.IsValid)
            {
                var token = HttpContext.Session.GetString(SD.SessionToken);
                var res = await _service.CreateAsync<APIResponse>(model, token);
                if (res != null && res.IsSuccess)
                {
                    return RedirectToAction(nameof(IndexVilla));
                }
            }
            return View();
        }

        // REMOVE
        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteVilla(int id)
        {
            var res = await _service.GetAsync<APIResponse>(id);
            if(res != null && res.IsSuccess)
            {
                return View(JsonConvert.DeserializeObject<VillaDTO>(JsonConvert.SerializeObject(res.Result)));
            }
            return NotFound(res);
        }
        [HttpPost]
        [Authorize(Roles = "admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteVilla(int id, bool trash = true)
        {
            if (id > 0)
            {
                var token = HttpContext.Session.GetString(SD.SessionToken);
                var res = await _service.DeleteAsync<APIResponse>(id, token);
                if (res != null && res.IsSuccess)
                {
                    TempData["success"] = $"Removed successfully item with id {id}";
                    return RedirectToAction(nameof(IndexVilla));
                }
                else
                {
                    TempData["error"] = $"Failed to remove item with id {id}";
                    return BadRequest(res);
                }
            }
            TempData["error"] = $"Id {id} is not valid!";
            return RedirectToAction(nameof(IndexVilla));
        }

        // UPDATE
        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> UpdateVilla(int id)
        {
            var res = await _service.GetAsync<APIResponse>(id);
            if(res != null && res.IsSuccess)
            {
                var villaDTO = JsonConvert.DeserializeObject<VillaDTO>(JsonConvert.SerializeObject(res.Result));
                return View(_mapper.Map<VillaUpdateDTO>(villaDTO));
            }
            return NotFound(res);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> UpdateVilla(VillaUpdateDTO villaUpdateDTO)
        {
            if (ModelState.IsValid)
            {
                var token = HttpContext.Session.GetString(SD.SessionToken);
                var res = await _service.UpdateAsync<APIResponse>(villaUpdateDTO, token);
                if(res != null && res.IsSuccess)
                {
                    TempData["success"] = $"Updated successfully item with id {villaUpdateDTO.Id}";
                    return RedirectToAction(nameof(IndexVilla));
                }
                else
                {
                    TempData["error"] = $"Failed to remove item with id {villaUpdateDTO.Id}";
                    return BadRequest(res);
                }
            }
            TempData["error"] = $"Something went wrong!";
            return View();
        }
    }
}

MagicVilla_Web/Views/Villa/CreateVilla.cshtml
@using MagicVilla_Web.Models.Dto.VillaDTO;
@model VillaDTO

<form asp-action="CreateVilla" asp-controller="Villa" method="post">
    <br />
    <div class="container border p-3">
        <h1 class="h2 text-primary">Create Villa</h1>
        <hr />

        <div class="row gy-3">
            @*NAME*@
            <div class="col-12">
                <div class="row">
                    <div class="col-12 col-md-2">
                        <label asp-for="Name" class="form-label">Name</label>
                    </div>
                    <div class="col-12 col-md-10">
                        <input type="text" class="form-control" asp-for="Name" />
                        <span asp-validation-for="Name" class="text-danger fs-6"></span>
                    </div>
                </div>
            </div>
            @*Rate*@
            <div class="col-12">
                <div class="row">
                    <div class="col-12 col-md-2">
                        <label asp-for="Rate" class="form-label">Rate</label>
                    </div>
                    <div class="col-12 col-md-10">
                        <input type="number" class="form-control" asp-for="Rate" />
                        <span asp-validation-for="Rate" class="text-danger fs-6"></span>
                    </div>
                </div>
            </div>
            @*Details*@
            <div class="col-12">
                <div class="row">
                    <div class="col-12 col-md-2">
                        <label asp-for="Details" class="form-label">Details</label>
                    </div>
                    <div class="col-12 col-md-10">
                        <textarea class="form-control" rows="3" asp-for="Details"></textarea>
                        <span asp-validation-for="Details" class="text-danger fs-6"></span>
                    </div>
                </div>
            </div>
            @*Sqft*@
            <div class="col-12">
                <div class="row">
                    <div class="col-12 col-md-2">
                        <label asp-for="Sqft" class="form-label">Sqft</label>
                    </div>
                    <div class="col-12 col-md-10">
                        <input type="number" class="form-control" asp-for="Sqft" />
                        <span asp-validation-for="Sqft" class="text-danger fs-6"></span>
                    </div>
                </div>
            </div>
            @*Ocupancy*@
            <div class="col-12">
                <div class="row">
                    <div class="col-12 col-md-2">
                        <label asp-for="Occupancy" class="form-label">Occupancy</label>
                    </div>
                    <div class="col-12 col-md-10">
                        <input type="number" class="form-control" asp-for="Occupancy" />
                        <span asp-validation-for="Occupancy" class="text-danger fs-6"></span>
                    </div>
                </div>
            </div>
            @*ImageUrl*@
            <div class="col-12">
                <div class="row">
                    <div class="col-12 col-md-2">
                        <label asp-for="ImageUrl" class="form-label">ImageUrl</label>
                    </div>
                    <div class="col-12 col-md-10">
                        <input type="tel" class="form-control" asp-for="ImageUrl" />
                        <span asp-validation-for="ImageUrl" class="text-danger fs-6"></span>
                    </div>
                </div>
            </div>
            @*Amenity*@
            <div class="col-12">
                <div class="row">
                    <div class="col-12 col-md-2">
                        <label asp-for="Amenity" class="form-label">Amenity</label>
                    </div>
                    <div class="col-12 col-md-10">
                        <input type="number" class="form-control" asp-for="Amenity" />
                        <span asp-validation-for="Amenity" class="text-danger fs-6"></span>
                    </div>
                </div>
            </div>
            @*Buttons*@
            <div class="col-12 offset-md-2 col-md-10">
                <div class="row g-3">
                    <div class="col-6">
                        <button class="btn btn-primary w-100" type="submit">Create</button>
                    </div>
                    <div class="col-6">
                        <a class="btn btn-secondary w-100" asp-action="IndexVilla" asp-controller="Villa">Cancel</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts {
@*    <partial name="_ValidationScriptsPartial" />*@
}

MagicVilla_Web/Views/Villa/DeleteVilla.cshtml
@using MagicVilla_Web.Models.Dto.VillaDTO;
@model VillaDTO

<form asp-action="DeleteVilla" asp-controller="Villa" method="post">
    <input asp-for="Id" hidden readonly />
    <br />
    <div class="container border p-3">
        <h1 class="h2 text-primary">Delete Villa</h1>
        <hr />

        <div class="row gy-3">
            @*NAME*@
            <div class="col-12">
                <div class="row">
                    <div class="col-12 col-md-2">
                        <label asp-for="Name" class="form-label">Name</label>
                    </div>
                    <div class="col-12 col-md-10">
                        <input type="text" class="form-control" asp-for="Name" readonly disabled/>
                    </div>
                </div>
            </div>
            @*Rate*@
            <div class="col-12">
                <div class="row">
                    <div class="col-12 col-md-2">
                        <label asp-for="Rate" class="form-label">Rate</label>
                    </div>
                    <div class="col-12 col-md-10">
                        <input type="number" class="form-control" asp-for="Rate" readonly disabled />
                    </div>
                </div>
            </div>
            @*Details*@
            <div class="col-12">
                <div class="row">
                    <div class="col-12 col-md-2">
                        <label asp-for="Details" class="form-label">Details</label>
                    </div>
                    <div class="col-12 col-md-10">
                        <textarea class="form-control" rows="3" asp-for="Details" readonly disabled ></textarea>
                    </div>
                </div>
            </div>
            @*Sqft*@
            <div class="col-12">
                <div class="row">
                    <div class="col-12 col-md-2">
                        <label asp-for="Sqft" class="form-label">Sqft</label>
                    </div>
                    <div class="col-12 col-md-10">
                        <input type="number" class="form-control" asp-for="Sqft" readonly disabled />
                    </div>
                </div>
            </div>
            @*Ocupancy*@
            <div class="col-12">
                <div class="row">
                    <div class="col-12 col-md-2">
                        <label asp-for="Occupancy" class="form-label">Occupancy</label>
                    </div>
                    <div class="col-12 col-md-10">
                        <input type="number" class="form-control" asp-for="Occupancy" readonly disabled />
                    </div>
                </div>
            </div>
            @*ImageUrl*@
            <div class="col-12">
                <div class="row">
                    <div class="col-12 col-md-2">
                        <label asp-for="ImageUrl" class="form-label">ImageUrl</label>
                    </div>
                    <div class="col-12 col-md-10">
                        <input type="tel" class="form-control" asp-for="ImageUrl" readonly disabled />
                    </div>
                </div>
            </div>
            @*Amenity*@
            <div class="col-12">
                <div class="row">
                    <div class="col-12 col-md-2">
                        <label asp-for="Amenity" class="form-label">Amenity</label>
                    </div>
                    <div class="col-12 col-md-10">
                        <input type="number" class="form-control" asp-for="Amenity" readonly disabled />
                    </div>
                </div>
            </div>
            @*Buttons*@
            <div class="col-12 offset-md-2 col-md-10">
                <div class="row g-3">
                    <div class="col-6">
                        <button class="btn btn-danger w-100" type="submit">Delete</button>
                    </div>
                    <div class="col-6">
                        <a class="btn btn-secondary w-100" asp-action="IndexVilla" asp-controller="Villa">Cancel</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @*    <partial name="_ValidationScriptsPartial" />*@
}

MagicVilla_Web/Views/Villa/IndexVilla.cshtml
@using MagicVilla_Web.Models.Dto.VillaDTO;
@model IEnumerable<VillaDTO>
@{
    var index = 0;
}
<br />
<div class="container p-4 border">
    <div class="row pb-2">
        <div class="col-md-6 col-12">
            <h1 class="h2 text-info text-center text-md-start">Villa List</h1>
        </div>
        <div class="col-md-6 col-12 d-md-flex justify-content-end">
            <a class="btn btn-outline-primary d-flex justify-content-center align-items-center" asp-action="CreateVilla" asp-controller="Villa">
                <i class="bi bi-plus-square me-2"></i>
                Create New Villa
            </a>
        </div>
    </div>
    <div class="table-responsive">
        <table class="table table-hover table-striped">
            <caption>List of villas</caption>
            <thead class="table-primary">
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Occupancy</th>
                    <th>Price</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    index++;
                    <tr>
                        <th scope="col">@index</th>
                        <td>@item.Name</td>
                        <td>@item.Occupancy</td>
                        <td>@item.Rate.ToString("c")</td>
                        <td class="d-md-flex justify-content-end">
                            <a class="btn btn-success me-md-3 mb-md-0 mb-1 text-center" asp-action="UpdateVilla" asp-controller="Villa" asp-route-id="@item.Id">
                                <i class="bi bi-pencil-square"></i>
                            </a>
                            <a class="btn btn-danger text-center" asp-action="DeleteVilla" asp-controller="Villa" asp-route-id="@item.Id">
                                <i class="bi bi-trash"></i>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

MagicVilla_Web/Views/Villa/UpdateVilla.cshtml
@using MagicVilla_Web.Models.Dto.VillaDTO;
@model VillaUpdateDTO

<form asp-action="UpdateVilla" asp-controller="Villa" method="post">
    <input asp-for="Id" hidden readonly/>
    <br />
    <div class="container border p-3">
        <h1 class="h2 text-primary">Create Villa</h1>
        <hr />

        <div class="row gy-3">
            @*NAME*@
            <div class="col-12">
                <div class="row">
                    <div class="col-12 col-md-2">
                        <label asp-for="Name" class="form-label">Name</label>
                    </div>
                    <div class="col-12 col-md-10">
                        <input type="text" class="form-control" asp-for="Name" />
                        <span asp-validation-for="Name" class="text-danger fs-6"></span>
                    </div>
                </div>
            </div>
            @*Rate*@
            <div class="col-12">
                <div class="row">
                    <div class="col-12 col-md-2">
                        <label asp-for="Rate" class="form-label">Rate</label>
                    </div>
                    <div class="col-12 col-md-10">
                        <input type="number" class="form-control" asp-for="Rate" />
                        <span asp-validation-for="Rate" class="text-danger fs-6"></span>
                    </div>
                </div>
            </div>
            @*Details*@
            <div class="col-12">
                <div class="row">
                    <div class="col-12 col-md-2">
                        <label asp-for="Details" class="form-label">Details</label>
                    </div>
                    <div class="col-12 col-md-10">
                        <textarea class="form-control" rows="3" asp-for="Details"></textarea>
                        <span asp-validation-for="Details" class="text-danger fs-6"></span>
                    </div>
                </div>
            </div>
            @*Sqft*@
            <div class="col-12">
                <div class="row">
                    <div class="col-12 col-md-2">
                        <label asp-for="Sqft" class="form-label">Sqft</label>
                    </div>
                    <div class="col-12 col-md-10">
                        <input type="number" class="form-control" asp-for="Sqft" />
                        <span asp-validation-for="Sqft" class="text-danger fs-6"></span>
                    </div>
                </div>
            </div>
            @*Ocupancy*@
            <div class="col-12">
                <div class="row">
                    <div class="col-12 col-md-2">
                        <label asp-for="Occupancy" class="form-label">Occupancy</label>
                    </div>
                    <div class="col-12 col-md-10">
                        <input type="number" class="form-control" asp-for="Occupancy" />
                        <span asp-validation-for="Occupancy" class="text-danger fs-6"></span>
                    </div>
                </div>
            </div>
            @*ImageUrl*@
            <div class="col-12">
                <div class="row">
                    <div class="col-12 col-md-2">
                        <label asp-for="ImageUrl" class="form-label">ImageUrl</label>
                    </div>
                    <div class="col-12 col-md-10">
                        <input type="tel" class="form-control" asp-for="ImageUrl" />
                        <span asp-validation-for="ImageUrl" class="text-danger fs-6"></span>
                    </div>
                </div>
            </div>
            @*Amenity*@
            <div class="col-12">
                <div class="row">
                    <div class="col-12 col-md-2">
                        <label asp-for="Amenity" class="form-label">Amenity</label>
                    </div>
                    <div class="col-12 col-md-10">
                        <input type="number" class="form-control" asp-for="Amenity" />
                        <span asp-validation-for="Amenity" class="text-danger fs-6"></span>
                    </div>
                </div>
            </div>
            @*Buttons*@
            <div class="col-12 offset-md-2 col-md-10">
                <div class="row g-3">
                    <div class="col-6">
                        <button class="btn btn-success w-100" type="submit">Update</button>
                    </div>
                    <div class="col-6">
                        <a class="btn btn-secondary w-100" asp-action="IndexVilla" asp-controller="Villa">Cancel</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @*    <partial name="_ValidationScriptsPartial" />*@
}