MagicVilla_Web/Controllers/VillaNumberController.cs
using MagicVilla_Utility;
using MagicVilla_Web.Models;
using MagicVilla_Web.Models.Dto.VillaDTO;
using MagicVilla_Web.Models.Dto.VillaNumberDTO;
using MagicVilla_Web.Models.ViewModels;
using MagicVilla_Web.Services.IServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.Data;

namespace MagicVilla_Web.Controllers
{
    public class VillaNumberController : Controller
    {
        private readonly IVillaNumberService _villaNumberService;
        private readonly IVillaService _villaService;
        public VillaNumberController(IVillaNumberService villaNumberService, IVillaService villaService)
        {
            _villaNumberService = villaNumberService;
            _villaService = villaService;
        }

        // GET ALL
        [HttpGet]
        public async Task<IActionResult> IndexVillaNumber()
        {
            var res = await _villaNumberService.GetAllAsync<APIResponse>();
            if (res != null && res.IsSuccess)
            {
                var model = JsonConvert.DeserializeObject<List<VillaNumberDTO>>(JsonConvert.SerializeObject(res.Result));
                return View(model);
            }
            return BadRequest(res);
        }

        // CREATE
        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> CreateVillaNumber()
        {
            var res = await _villaService.GetAllAsync<APIResponse>();
            if(res != null && res.IsSuccess)
            {
                var viewModel = new VillaNumberCreateVM();
                var villaList = JsonConvert.DeserializeObject<List<VillaDTO>>(JsonConvert.SerializeObject(res.Result));
                if(villaList != null)
                {
                    viewModel.VillaList = villaList.Select(villa => new SelectListItem()
                    {
                        Value = villa.Id.ToString(),
                        Text = villa.Name,
                    });
                    return View(viewModel);
                }
                return BadRequest();
            }
            return BadRequest();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> CreateVillaNumber([FromForm] VillaNumberCreateVM villaNumberCreateVM)
        {
            if (ModelState.IsValid)
            {
                var token = HttpContext.Session.GetString(SD.SessionToken);
                var res = await _villaNumberService.CreateAsync<APIResponse>(villaNumberCreateVM.VillaNumber, token);
                if (res != null && res.IsSuccess)
                {
                    return RedirectToAction(nameof(IndexVillaNumber));
                }
            }

            var villaNumberCreateDTO = villaNumberCreateVM.VillaNumber;
            var villaRes = await _villaService.GetAllAsync<APIResponse>();
            if (villaRes != null && villaRes.IsSuccess)
            {
                var viewModel = new VillaNumberCreateVM() { };
                var villaList = JsonConvert.DeserializeObject<List<VillaDTO>>(JsonConvert.SerializeObject(villaRes.Result));
                if (villaList != null && villaNumberCreateDTO != null)
                {
                    viewModel.VillaNumber = villaNumberCreateDTO;
                    viewModel.VillaList = villaList.Select(villa =>
                    {
                        bool isSelected = villaNumberCreateDTO.VillaId == villa.Id;
                        return new SelectListItem()
                        {
                            Value = villa.Id.ToString(),
                            Text = villa.Name,
                            Selected = isSelected,
                        };
                    });
                    return View(viewModel);
                }
            }
            return BadRequest();
        }

        // UPDATE
        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> UpdateVillaNumber([FromQuery] int villaNo)
        {
            var viewModel = new VillaNumberUpdateVM();
            var res = await _villaNumberService.GetAsync<APIResponse>(villaNo);
            if (res != null && res.IsSuccess)
            {
                viewModel.VillaNumber = JsonConvert.DeserializeObject<VillaNumberUpdateDTO>(JsonConvert.SerializeObject(res.Result));
            }

            // Get villa select
            var villaRes = await _villaService.GetAllAsync<APIResponse>();
            if (villaRes != null && villaRes.IsSuccess)
            {
                var villaList = JsonConvert.DeserializeObject<List<VillaDTO>>(JsonConvert.SerializeObject(villaRes.Result));
                if (villaList != null)
                {
                    viewModel.VillaList = villaList.Select(villa => new SelectListItem()
                    {
                        Value = villa.Id.ToString(),
                        Text = villa.Name,
                        Selected = villa.Id == viewModel.VillaNumber.VillaId,
                    });
                    return View(viewModel);
                }
                return BadRequest();
            }
            return BadRequest();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> UpdateVillaNumber([FromForm]VillaNumberUpdateVM villaNumberUpdateVM)
        {
            if (ModelState.IsValid)
            {
                var token = HttpContext.Session.GetString(SD.SessionToken);
                var res = await _villaNumberService.UpdateAsync<APIResponse>(villaNumberUpdateVM.VillaNumber, token);
                if (res != null && res.IsSuccess)
                {
                    return RedirectToAction(nameof(IndexVillaNumber));
                }
            }

            var villaRes = await _villaService.GetAllAsync<APIResponse>();
            if (villaRes != null && villaRes.IsSuccess)
            {
                var villaList = JsonConvert.DeserializeObject<List<VillaDTO>>(JsonConvert.SerializeObject(villaRes.Result));
                if (villaList != null)
                {
                    villaNumberUpdateVM.VillaList = villaList.Select(villa => new SelectListItem()
                    {
                        Value = villa.Id.ToString(),
                        Text = villa.Name,
                        Selected = villa.Id == villaNumberUpdateVM.VillaNumber.VillaId,
                    });
                    return View(villaNumberUpdateVM);
                }
                return BadRequest();
            }
            return BadRequest();
        }

        [HttpGet]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteVillaNumber([FromQuery] int villaNo)
        {
            var res = await _villaNumberService.GetAsync<APIResponse>(villaNo);
            if (res != null && res.IsSuccess)
            {
                return View(JsonConvert.DeserializeObject<VillaNumberDTO>(JsonConvert.SerializeObject(res.Result)));
            }
          
            return BadRequest();
        }
        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteVillaNumber([FromForm] VillaNumberDTO villaNumberDTO)
        {
            var token = HttpContext.Session.GetString(SD.SessionToken);
            var res = await _villaNumberService.DeleteAsync<APIResponse>(villaNumberDTO.VillaNo, token);
            if (res != null && res.IsSuccess)
            {
                return RedirectToAction(nameof(IndexVillaNumber));
            }
            return BadRequest(res);

        }
    }
}

MagicVilla_Web/Views/VillaNumber/CreateVillaNumber.cshtml
@using MagicVilla_Web.Models.ViewModels;
@model VillaNumberCreateVM

<form asp-action="CreateVillaNumber" asp-controller="VillaNumber" method="post" enctype="multipart/form-data">
    <br />
    <div class="container border p-3">
        <h1 class="h2 text-primary">Create Villa</h1>
        <hr />

        <div class="row gy-3">
            @*Villa No*@
            <div class="col-12">
                <div class="row gy-1">
                    <div class="col-12 col-md-2">
                        <label asp-for="VillaNumber.VillaNo" class="form-label">Villa No</label>
                    </div>
                    <div class="col-12 col-md-10">
                        <input type="text" class="form-control" asp-for="VillaNumber.VillaNo" />
                        <span asp-validation-for="VillaNumber.VillaNo" class="text-danger fs-6"></span>
                    </div>
                </div>
            </div>
            @*Special Details*@
            <div class="col-12">
                <div class="row gy-1">
                    <div class="col-12 col-md-2">
                        <label asp-for="VillaNumber.SpecialDetails" class="form-label">SpecialDetails</label>
                    </div>
                    <div class="col-12 col-md-10">
                        <textarea class="form-control" rows="3" asp-for="VillaNumber.SpecialDetails"></textarea>
                        <span asp-validation-for="VillaNumber.SpecialDetails" class="text-danger fs-6"></span>
                    </div>
                </div>
            </div>
            @*Villa Select*@
            <div class="col-12">
                <div class="row gy-1">
                    <div class="col-12 col-md-2">
                        <label asp-for="VillaNumber.VillaId" class="form-label">Villa</label>
                    </div>
                    <div class="col-12 col-md-10">
                        <select asp-for="VillaNumber.VillaId" asp-items="Model.VillaList" class="form-control">
                            <option value="0" disabled selected>-- Select Villa --</option>
                        </select>
                        <span asp-validation-for="VillaNumber.VillaId" class="text-danger fs-6"></span>
                    </div>
                </div>
            </div>
            @*Buttons*@
            <div class="col-12 offset-md-2 col-md-10">
                <div class="row g-3">
                    <div class="col-6">
                        <button class="btn btn-primary w-100" type="submit">Create</button>
                    </div>
                    <div class="col-6">
                        <a class="btn btn-secondary w-100" asp-action="IndexVillaNumber" asp-controller="VillaNumber">Cancel</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @*    <partial name="_ValidationScriptsPartial" />*@
}

MagicVilla_Web/Views/VillaNumber/DeleteVillaNumber.cshtml
@using MagicVilla_Web.Models.Dto.VillaNumberDTO;
@model VillaNumberDTO

<form asp-action="DeleteVillaNumber" asp-controller="VillaNumber" method="post" >
    <input asp-for="VillaNo" hidden readonly />
    <br />
    <div class="container border p-3">
        <h1 class="h2 text-primary">Remove Villa</h1>
        <hr />

        <div class="row gy-3">
            @*Villa No*@
            <div class="col-12">
                <div class="row gy-1">
                    <div class="col-12 col-md-2">
                        <label asp-for="VillaNo" class="form-label">Villa No</label>
                    </div>
                    <div class="col-12 col-md-10">
                        <input type="text" class="form-control" asp-for="VillaNo" disabled readonly />
                    </div>
                </div>
            </div>
            @*Special Details*@
            <div class="col-12">
                <div class="row gy-1">
                    <div class="col-12 col-md-2">
                        <label asp-for="SpecialDetails" class="form-label">SpecialDetails</label>
                    </div>
                    <div class="col-12 col-md-10">
                        <textarea disabled readonly class="form-control" rows="3" asp-for="SpecialDetails"></textarea>
                    </div>
                </div>
            </div>
            @*Villa Select*@
            <div class="col-12">
                <div class="row gy-1">
                    <div class="col-12 col-md-2">
                        <label asp-for="VillaId" class="form-label">Villa</label>
                    </div>
                    <div class="col-12 col-md-10">
                        <select asp-for="VillaId" class="form-control" disabled>
                            <option value="0" disabled selected >-- Select Villa --</option>
                            <option selected value="@Model.VillaId" >@Model.Villa.Name</option>
                        </select>
                    </div>
                </div>
            </div>
            @*Buttons*@
            <div class="col-12 offset-md-2 col-md-10">
                <div class="row g-3">
                    <div class="col-6">
                        <button class="btn btn-danger w-100" type="submit">Delete</button>
                    </div>
                    <div class="col-6">
                        <a class="btn btn-secondary w-100" asp-action="IndexVillaNumber" asp-controller="VillaNumber">Cancel</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @*    <partial name="_ValidationScriptsPartial" />*@
}

MagicVilla_Web/Views/VillaNumber/IndexVillaNumber.cshtml
@using MagicVilla_Web.Models.Dto.VillaNumberDTO;
@model IEnumerable<VillaNumberDTO>

<br />
<div class="container p-4 border">
    <div class="row pb-2">
        <div class="col-md-6 col-12">
            <h1 class="h2 text-info text-center text-md-start">Villa List</h1>
        </div>
        <div class="col-md-6 col-12 d-md-flex justify-content-end">
            <a class="btn btn-outline-primary d-flex justify-content-center align-items-center" asp-action="CreateVillaNumber" asp-controller="VillaNumber">
                <i class="bi bi-plus-square me-2"></i>
                Create New Villa Number
            </a>
        </div>
    </div>
    <div class="table-responsive">
        <table class="table table-hover table-striped">
            <caption>List of villa number</caption>
            <thead class="table-primary">
                <tr>
                    <th>Villa No</th>
                    <th>Name</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <th scope="col">@item.VillaNo</th>
                        <td>@item.Villa.Name</td>
                        <td class="d-md-flex justify-content-end">
                            <a class="btn btn-success me-md-3 mb-md-0 mb-1 text-center" asp-action="UpdateVillaNumber" asp-controller="VillaNumber" asp-route-villaNo="@item.VillaNo">
                                <i class="bi bi-pencil-square"></i>
                            </a>
                            <a class="btn btn-danger text-center" asp-action="DeleteVillaNumber" asp-controller="VillaNumber" asp-route-villaNo="@item.VillaNo">
                                <i class="bi bi-trash"></i>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

MagicVilla_Web/Views/VillaNumber/UpdateVillaNumber.cshtml
@using MagicVilla_Web.Models.ViewModels;
@model VillaNumberUpdateVM

<form asp-action="UpdateVillaNumber" asp-controller="VillaNumber" method="post" enctype="multipart/form-data" >
    <br />
    <div class="container border p-3">
        <h1 class="h2 text-primary">Update Villa</h1>
        <hr />

        <div class="row gy-3">
            @*Villa No*@
            <div class="col-12">
                <div class="row gy-1">
                    <div class="col-12 col-md-2">
                        <label asp-for="VillaNumber.VillaNo" class="form-label">Villa No</label>
                    </div>
                    <div class="col-12 col-md-10">
                        <input type="text" class="form-control" asp-for="VillaNumber.VillaNo" />
                        <span asp-validation-for="VillaNumber.VillaNo" class="text-danger fs-6"></span>
                    </div>
                </div>
            </div>
            @*Special Details*@
            <div class="col-12">
                <div class="row gy-1">
                    <div class="col-12 col-md-2">
                        <label asp-for="VillaNumber.SpecialDetails" class="form-label">SpecialDetails</label>
                    </div>
                    <div class="col-12 col-md-10">
                        <textarea class="form-control" rows="3" asp-for="VillaNumber.SpecialDetails"></textarea>
                        <span asp-validation-for="VillaNumber.SpecialDetails" class="text-danger fs-6"></span>
                    </div>
                </div>
            </div>
            @*Villa Select*@
            <div class="col-12">
                <div class="row gy-1">
                    <div class="col-12 col-md-2">
                        <label asp-for="VillaNumber.VillaId" class="form-label">Villa</label>
                    </div>
                    <div class="col-12 col-md-10">
                        <select asp-for="VillaNumber.VillaId" asp-items="Model.VillaList" class="form-control">
                            <option value="0" disabled>-- Select Villa --</option>
                        </select>
                        <span asp-validation-for="VillaNumber.VillaId" class="text-danger fs-6"></span>
                    </div>
                </div>
            </div>
            @*Buttons*@
            <div class="col-12 offset-md-2 col-md-10">
                <div class="row g-3">
                    <div class="col-6">
                        <button class="btn btn-primary w-100" type="submit">Update</button>
                    </div>
                    <div class="col-6">
                        <a class="btn btn-secondary w-100" asp-action="IndexVillaNumber" asp-controller="VillaNumber">Cancel</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @*    <partial name="_ValidationScriptsPartial" />*@
}